services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: xhepo
      POSTGRES_PASSWORD: xhepower
      POSTGRES_DB: trazabilidad
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
